Rename do_card_from_hand_to_gauge
daniel-k-taylor/exceedgameclient pull request #142
Opened 2024-04-19 20:02 UTC by rngesus-wept

It moves the card from hand to *wherever the current decision wants them to go*.

There are no more hits for `do_card_from_hand_to_gauge` in the codebase, and all the unit tests pass, so this should be complete and correct.

2024-04-20 00:30 UTC, daniel-k-taylor requested changes
I think this breaks remote play.
You need to rename the action too.

Please look at _process_game_message and make sure this works.
Make sure you test playing with yourself with 2 clients and trigger this effect.

2024-04-20 00:30 UTC, daniel-k-taylor commented on scenes/game/remote_game.gd
>  func process_card_from_hand_to_gauge(action_message) -> void:
you didn't rename this

2024-04-20 00:30 UTC, daniel-k-taylor commented on scenes/game/game_wrapper.gd
>  func submit_card_from_hand_to_gauge(player : Enums.PlayerId, card_ids : Array) -> bool:
you didn't rename this

2024-04-20 00:30 UTC, daniel-k-taylor commented on scenes/game/remote_game.gd
>  		'action_type': 'action_card_from_hand_to_gauge',
Ideally we would update this too. But do we care about replay compatibility?
I'd say probably not at this point?

Actually, isn't this how these functions are called? You renaming that is going to break it.

2024-04-22 19:07 UTC, rngesus-wept commented
Updated, PTAL

2024-04-24 01:43 UTC, daniel-k-taylor approved these changes

2024-04-24 06:19 UTC, merged