Shovel/Shield Knight
daniel-k-taylor/exceedgameclient pull request #17
Opened 2024-01-19 03:56 UTC by Mach131

probably extremely messy but all the tests are passing

2024-01-19 06:16 UTC, daniel-k-taylor requested changes

2024-01-19 06:16 UTC, daniel-k-taylor commented on scenes/game/local_game.gd
> +			performing_player.ignore_push_and_pull = true
maybe we should call this one "ignore_push_and_pull_boost_bonus" just to be super clear and not confuse with the other one
Or maybe passive_bonus? passive_boost?

2024-01-19 06:16 UTC, daniel-k-taylor commented on scenes/game/local_game.gd
> +		# Currently assumes these will be armor-related; probably breaks if choices get involved
almost certainly breaks if choices get involved and block is also involved.
If someone has multiple when_hit that are choices or need to be ordered and interact with block, we'll have to add the same kind of effect list stuff as other timing windows.
For now, this should be fine though.

2024-01-19 06:16 UTC, daniel-k-taylor commented on scenes/game/local_game.gd
> +			events += do_effects_for_timing("when_hit", defense_player, active_strike.initiator_card, next_state)
I'm not a huge fan of passing in the card when it doesn't matter, but I see you're doing that as just a way to get the character effects....
Maybe just do what reshuffle_discard does?
var effects = get_character_effects_at_timing("on_reshuffle")
for effect in effects:
    events += parent.do_effect_if_condition_met(self, -1, effect, local_conditions)

I don't want to read this later and accidentally think it does more than it does.

2024-01-19 06:16 UTC, daniel-k-taylor commented on scenes/game/local_game.gd
> +		if cannot_move:
Okay, I saw later why this was here from the swap places effect.
Should be fine.

2024-01-19 18:20 UTC, Mach131 commented on scenes/game/ai/ai_policy_rules.gd
> +		distance_after_effects = abs(buddy_location - opponent_location)
it be like that; at least it's less likely to throw out shield knight attacks when she's nowhere near you

2024-01-19 18:20 UTC, Mach131 commented on scenes/game/local_game.gd
> +		if not do_not_cleanup_buddy_this_turn and not buddy_always_on_field:
are there any characters like that? will prob just make it starting_offset to be safe but might be able to get away with a bool

2024-01-19 18:34 UTC, Mach131 commented on scenes/game/local_game.gd
> +		if cannot_move:
yee hopefully shouldn't break regular movement

2024-01-19 19:37 UTC, Mach131 commented on scenes/game/local_game.gd
> +			var effects = get_character_effects_at_timing("on_advance_or_close")
I think I got it, just had to do a bit of extra stuff to make sure i'm not losing the and effects

2024-01-20 03:47 UTC, daniel-k-taylor approved these changes

2024-01-20 03:47 UTC, daniel-k-taylor commented on scenes/game/game.gd
> +			"cancel_text": "Name Exodia",
funny, but maybe just "Name Nothing - Reveal Hand" is better

2024-01-20 03:47 UTC, daniel-k-taylor commented on scenes/game/game.gd
> +			"cancel_text": "Name Exodia",
I guess you could leave it Exodia, but just add the Reveal Hand part to be clear what is going on for people who don't get it

2024-01-20 03:49 UTC, daniel-k-taylor approved these changes

2024-01-20 03:49 UTC, merged